### ISSUE TITLE
questions/comments about demo

### ISSUE THREAD

**Issue by scottaohara** [tabvengers/spicy-sections#19]
saw dave's article last night and got to poking around the demo this morning.  a couple bits concerning the demo.

* what was the reason for using `aria-expanded` on the tab-version of the component?  that isn't generally necessary/expected as the selected state already indicates the associated panel is opened?  
* There seems to be a bug with keyboard functionality (at least in the codepen demo)  the now disclosure widget controls don't allow for enter or space keys to open.  The demo that Dave made (bookshelf) has space key activation behavior in the accordion state.  being just a demo, is this expected that it's not keyboard operable?  if so, then never mind :)
* When the tab widget version collapses into the accordion UI, is there a way to ensure that the previously exposed tab panel becomes an expanded disclosure widget?  At least, specifically in the situation where a user had explicitly selected a tab, and then for legitimate reasons, zooms in their browser - the previously opened tab is now a collapsed disclosure widget.  So now that user needs to re-locate and re-open that panel of content.

**Comment by bkardell** [comment]
After our meeting today we agreed the first two questions have been resolved, and the third one probably deserves its own issue (perhaps more than one). I have a few issues to open, or if @scottaohara gets to it first, let's please mention that it came from this issue - and I'll close this one in the meantime.
